# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff
        pip install -r requirements.txt
    - name: Lint for errors
      run: |
        # stop the build if there are Python syntax errors or undefined names
        ruff check --select=E9,F63,F7,F82 --output-format full --no-fix
    - name: Lint for warnings
      run: |
        # exit-zero treats all errors as warnings.
        ruff check --extend-ignore "PLR09","C901" --exit-zero --output-format concise --no-fix
    - name: Lint for complexity warnings
      run: |
        # exit-zero treats all errors as warnings.
        ruff check --select "PLR09" --exit-zero --output-format concise --no-fix
        ruff check --select "C901" --exit-zero --output-format concise --no-fix
